spring:
  datasource:
    username: summer
    password: summer
    url: jdbc:oracle:thin:@192.168.100.165:1521/orcl
    driver-class-name: oracle.jdbc.OracleDriver


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql:true

